version: '3'
services:
  frontend:
    container_name: touchbistro_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: musab/touchbistro_client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: touchbistro_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: musab/touchbistro_server
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    volumes:
      - ./server:/usr/src/app
